apiVersion: v1
kind: Service
metadata:
  name: healthy-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: healthy
  ports:
  - port: 80
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthy
  labels:
    app: healthy
spec:
  replicas: 2
  minReadySeconds: 10 #time to receive traffic after initialize (check if container crashes)
  selector:
    matchLabels:
      app: healthy
  template:
    metadata:
      labels:
        app: healthy
    spec:
      containers:
        - name: healthy
          image: gsg:spring-boot-healthy
          ports:
          - containerPort: 8080
          envFrom:
          - configMapRef:
              name: healthy-settings
